---
provisioner:
  name: chef_zero
  client_rb:
    node_name: 'test-node-name'
    no_lazy_load: true

driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '12.19' #'latest'
  customize:
    cpus: 2
    memory: 2048
    cpuexecutioncap: 75

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: 'ubuntu/precise64'
    run_list:
      - recipe[apt]
  - name: centos-7.2
    driver_config:
      box: 'centos/7'

suites:
  - name: known_hosts
    run_list:
      - recipe[ssh_test::known_hosts]
    attributes:
      ssh_test:
        known_hosts:
          test_entry: 'dummy5 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCe1poC4rUN8CoW+bWfij2KvY6wYhHdZsxbhyfwUVEclCDcjf4W9Xlso3dogVYXIlqdaeB7SqXmczvsOKl51UTE6Or7G7tiffwZoe4z4J1tRX9HCi+5ZOjUeLtvu6764mpMoTpEwFekER4osXosJw29Nu6cLeM+REpyH/RMZwpb1FUEIOptdupepWh7vlvv4fu0dw1ir0t2lHuW/QCmNh9umSsIxGSOJMnwt1ohk4LKYLykHEc3RRsWZS9rPjbNmAerrdbhF8FF5dyMi+rde5dcIApDmWz3hQwIrZdB+fF5oITVXulTsyhoERQyJf/70oWSECzTuO/jRudlx870bC7b'
  - name: config
    run_list:
      - recipe[ssh_test::config]
  - name: authorized_keys
    run_list:
      - recipe[ssh_test::authorized_keys]
